Update q-and-a.md
nuts-foundation/nuts-webpresence pull request #170
Opened 2023-07-03 13:12 UTC by Saldoo

Teksten aangepast:
Q&A: Verwijzing naar de Nuts Wiki
Wat is een Nuts node?

2023-07-04 07:17 UTC, woutslakhorst requested changes

2023-07-04 07:17 UTC, woutslakhorst commented on content/posts/q-and-a.md
> +De Nuts-node is een open-source software referentie-implementatie van de Nuts-specificatie. Iedereen heeft de mogelijkheid om een Nuts-node te ontwikkelen. De Nuts-node draait dan ook als component v
```
...
De Nuts-node draait dan ook als component van de gegevensverwerkende applicatie.
...
```
Dat klopt niet, de node draait als applicatie binnen de infrastructuur van de leverancier/partij/iemand.

2023-07-07 12:02 UTC, Saldoo reviewed
Zin aangepast: De Nuts-node draait als applicatie component binnen de infrastructuur van gegevensverwerkende programmatuur.

2023-07-10 06:59 UTC, woutslakhorst approved these changes

2023-07-10 06:59 UTC, merged