Update q-and-a.md
nuts-foundation/nuts-webpresence pull request #176
Opened 2023-07-10 11:17 UTC by Saldoo

2023-07-17 13:57 UTC, stevenvegt requested changes
Vanwaar al die html tags?

2023-07-31 09:42 UTC, Saldoo reviewed
Teksten aangepast met de juiste termen + eenheid van taal.

2023-07-31 11:25 UTC, stevenvegt requested changes

2023-07-31 11:25 UTC, stevenvegt commented on content/posts/q-and-a.md
> +samenwerken.Als basis hanteren we een set uitgangspunten, die we hebben gevat
```suggestion
samenwerken. Als basis hanteren we een set uitgangspunten, die we hebben gevat
```

2023-07-31 11:25 UTC, stevenvegt commented on content/posts/q-and-a.md
> +</details></p>
Deze lijken hier niet te horen
```suggestion
```

2023-08-01 07:59 UTC, Saldoo commented on content/posts/q-and-a.md
> +samenwerken.Als basis hanteren we een set uitgangspunten, die we hebben gevat
Spatie toegevoegd.

2023-10-06 09:01 UTC, Saldoo reviewed
Graag publiceren.

2023-10-06 09:06 UTC, reinkrul approved these changes

2023-10-06 09:06 UTC, reinkrul commented
Heeft approval van @stevenvegt nodig.

2023-10-13 12:44 UTC, stevenvegt approved these changes

2023-10-13 12:45 UTC, merged