Update documentatie.md
nuts-foundation/nuts-webpresence pull request #177
Opened 2023-07-10 11:22 UTC by Saldoo

2023-07-10 12:08 UTC, Saldoo commented
Input Marlene: Nuts standaarden kennen we niet. Dan beter de Nuts-specificaties (zie eenheid van taal) en Nuts-node. En Nuts-broncode hadden we nog niet apart in het eenheid van taal-document. Goed om deze toe te voegen, er staat wel al een beschrijving, maar niet expliciet uitgelicht als definitie. Ik denk dat het goed is dat we dan ook vermelden dat de Nuts-broncode Open Source beschikbaar is volgens de Creative Common licentie en dat dit inhoudt dat je aanpassingen ook aan de community ter beschikking stelt. Ik weet niet meer precies waar dit staat. Dat heeft Sergej vast in definitievorm in zijn community based developemnt aanpak. Hier moeten we een correcte tekst voor vinden.
identificeren van gebruikers, zie ik ook in eenheid van taal....ik twijfel even of dit wel helemaal klopt?. Daar moet Wout een uitspraak over doen.
wij vervangen : die in de Nuts-community is
demo-applicaties vervangen : demo-EHR ( en checken bij Tech team, wat daar de status van is en of er een link is die we kunnen opnemen)

2023-07-17 14:07 UTC, stevenvegt requested changes
Ik ben ook niet zo'n fan van die keywords, mogen er van mij wel uit.

2023-07-17 14:07 UTC, stevenvegt commented on content/posts/documentatie.md
> +&nbsp;
Waarom hier een nbsp?

2023-07-27 12:44 UTC, Saldoo commented on content/posts/documentatie.md
> +&nbsp;
verwijderd.

2023-07-27 12:48 UTC, Saldoo commented on content/posts/documentatie.md
> +De broncode van onze referentie-implementatie (de Nuts node) en de demo-applicaties die wij hebben ontwikkeld is zoals gezegd voor iedereen beschikbaar en staat online op het samenwerkingsplatform Gi
Link Github toegevoegd.

2023-07-27 13:04 UTC, Saldoo commented on content/posts/documentatie.md
> +&nbsp;
Bij wijzigingen plaatst GitHub er automatisch een nbsp bij.

2023-07-27 19:13 UTC, woutslakhorst approved these changes

2023-07-27 19:13 UTC, merged