Create meetings
nuts-foundation/nuts-webpresence pull request #182
Opened 2023-07-17 10:16 UTC by Saldoo

2023-07-17 13:51 UTC, stevenvegt commented
Ziet er uit alsof op deze pagina: https://nuts.nl/community/ ook al dingen over community meetings wordt gezegd. Hoe verhouden die zich tot elkaar?

2023-07-19 11:34 UTC, Saldoo commented
extensie .md toegevoegd.

2023-07-19 11:41 UTC, Saldoo commented
> Ziet er uit alsof op deze pagina: https://nuts.nl/community/ ook al dingen over community meetings wordt gezegd. Hoe verhouden die zich tot elkaar?
Steven: We gaan een extra menu toevoegen "Actueel". Eerst wil ik deze pagina even bekijken voordat ik deze direct link in een nieuw menu. "Actueel". Meer informatie kun je vinden in BaseCamp > Card Tables.  Deze is overigens niet aan jou persoonlijk toegewezen. Podcasts zullen wij bijvoorbeeld ook gaan koppelen aan dit nieuwe menu.

- Nuts in het nieuws
- Kalender
- Meetings 
- Podcasts

2023-07-31 10:18 UTC, Saldoo reviewed
Nieuwe pagina - deze wordt later aan een nieuw menu Actueel toegevoegd.

2023-07-31 11:43 UTC, stevenvegt requested changes

2023-07-31 11:43 UTC, stevenvegt commented on content/posts/meetings.md
> +NUTS maakt het mogelijk dat softwareapplicaties in de zorg met elkaar op een vertrouwelijke, veilige en toegankelijke manier kunnen communiceren. Tijdens onze maandelijkse communitymeetings praten wi
Misschien niet nodig om hier in het kort te vertellen wat Nuts mogelijk maakt, maar misschien wel handig om iets meer over de community meetings te vertellen. Ook waar de agenda staat en hoe je zelf iets kunt vertellen?

2023-07-31 11:43 UTC, stevenvegt commented on content/posts/meetings.md
> +* Kom naar één van onze meetings (zie de [kalender](/kalender) voor tijden en locaties)
Dit is nu een lijst met 1 bulletpoint. Beter weg te halen en dit stukje integreren met bovenstaande alinea.

2023-08-01 07:53 UTC, Saldoo reviewed
Link agenda + aanleveren agenda punten toegevoegd.

2023-09-27 09:39 UTC, reinkrul commented
Er wordt nog niet gelinkt naar deze pagina vanuit het menu (of vanuit een andere pagina). Ik heb de wijzigingen m.b.t. menu-structuur, dus deze pagina kan onder het juiste item gehangen worden denk ik?

2023-09-29 11:44 UTC, Saldoo commented
@reinkrul: In BaseCamp van Nuts staat de achterliggende informatie omtrent wijzigingen voor de websitte van Nuts.nl. 
Deze pagina moet inderdaad nog worden toegevoegd aan het menu Actueel. Echter dit kan ik pas doen als de pagina is gepubliceerd. 
Zie ook: https://3.basecamp.com/4451397/buckets/26487126/card_tables/cards/6355651573

2023-09-29 12:12 UTC, reinkrul approved these changes

2023-09-29 12:16 UTC, reinkrul commented
Toegevoegd aan menu "Actueel", alleen is er nu onder "Meedoen" een pagina "Community" met daarop een paragraaf "Community meetings" , en onder Actueel een pagina "Meetings", waarvan de titel "Community Meetings" is. Lijkt een beetje langs elkaar heen te gaan.

2023-10-06 08:52 UTC, Saldoo commented
Op basis van jullie input en inmiddels gedateerde content. Deze PR gesloten en verbeterpunten doorgevoerd op de pagina Community.

2023-10-06 08:52 UTC, closed without merging