Add files via upload
nuts-foundation/nuts-webpresence pull request #206
Opened 2023-10-06 09:14 UTC by Saldoo

Logo toegevoegd voor caroesel homepage.

2023-10-06 14:08 UTC, reinkrul commented
Dit is alleen de afbeelding, hiermee is hij nog niet toegevoegd aan de carrousel. Moet ik dat doen, of lukt dat jou zelf?

2023-10-13 12:48 UTC, Saldoo commented
@reinkrul: Dat klopt dat het alleen het bestand is. Maar ik kan deze pas toevoegen in participants.json zodra ik de verwijzing heb.

2023-10-13 12:49 UTC, stevenvegt requested changes
* Het logo hernoemen naar de naam van het bedrijf, bijv. syntilio.svg ipv e650b6a3-abb5-4a6d-bfc8-0ae756be0f0a.svg
* Logo toevoegen aan de html van het carousel.

2023-10-13 12:50 UTC, stevenvegt commented
> @reinkrul: Dat klopt dat het alleen het bestand is. Maar ik kan deze pas toevoegen in participants.json zodra ik de verwijzing heb.

Ik denk het niet toch? Je kunt in de branch https://github.com/nuts-foundation/nuts-webpresence/tree/Logo-Syntilio-carroussel-teogevoegd bestanden aanpassen?

2023-12-02 20:27 UTC, closed without merging